namespace: timhatdiehandandermaus

deployment:
  name: bus-frontend
  image: ghcr.io/blindfoldedsurgery/bus-frontend:__TAG__
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
  replicas: 2
  ports:
  - 5000
  labels:
    app: bus-frontend
  requests:
    cpu: 50m
    memory: 10Mi
  limit:
    cpu: 300m
    memory: 50Mi
  healthEndpoint: /health

service:
  name: bus-frontend
  port: 80
  targetPort: 5000
  appSelector: bus-frontend

ingress:
  secret: tls-bus-frontend
  issuer: letsencrypt-issuer
  name: bus-frontend
  frontend:
    hosts:
      - bus.timhatdiehandandermaus.consulting
      - tram.timhatdiehandandermaus.consulting
      - abfahrt.io
  images:
    hosts:
      - images.timhatdiehandandermaus.consulting
    path: /public/images

configmap:
  name: bus-frontend
  imagesBaseUrl: images.timhatdiehandandermaus.consulting
